# Generated by Django 4.0.3 on 2022-04-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=100)),
                ('nacimiento', models.DateField()),
                ('jerarquia', models.IntegerField()),
            ],
        ),
    ]
